# Generated by Django 4.1.3 on 2022-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(height_field=480, upload_to='seaborn_and_AI_app/templates/images', width_field=640)),
            ],
        ),
    ]
